import React from "react";

function ExperienceSection() {
  return (
    <section className="content-section experience-section">
      <div className="section-title">
        <p className="section-kicker section-kicker-blue">EXPERIENCE</p>
      </div>

      <div className="timeline">
        <article className="timeline-item">
          <div className="timeline-header">
            <h3>Web Developer Intern — GTS Active Company</h3>
            <span>Nov 2025 - May 2026</span>
          </div>
          <p>
            During my 6-month internship as a Web Developer at GTS Active Company, I developed
            and maintained responsive web applications using Vue.js, improving UI performance
            and usability. I designed and integrated RESTful APIs with Spring Boot, implemented
            Firebase Realtime Database for real-time synchronization and authentication, and
            worked with MongoDB and MySQL for data storage. Collaborated in an Agile (Scrum)
            team on feature development, debugging, and code reviews, and resolved performance
            issues to enhance application responsiveness and stability.
          </p>
        </article>

        <div className="projects-list">
          <h4 className="projects-title">Selected Projects</h4>

          <article className="timeline-item">
            <div className="timeline-header">
              <h3>IoT Factory Machine Monitoring System</h3>
              <span>Full Stack — Vue.js | Firebase Realtime Database</span>
            </div>
            <p>
              University project: developed a real-time monitoring system to track machine
              status and performance. Built a responsive dashboard with Vue.js and integrated
              Firebase Realtime Database for live updates and alert indicators.
            </p>
          </article>

          <article className="timeline-item">
            <div className="timeline-header">
              <h3>Tourism Management Application</h3>
              <span>Android — Java | Firebase</span>
            </div>
            <p>
              Developed an Android app with location services, interactive maps, and booking
              forms. Integrated Firebase for real-time data and authentication, and designed a
              user-friendly interface to improve travel planning.
            </p>
          </article>

          <article className="timeline-item">
            <div className="timeline-header">
              <h3>Student Marks Visualization App</h3>
              <span>Flask | Matplotlib</span>
            </div>
            <p>
              Built a web app to record and visualize student marks with interactive charts
              generated by Matplotlib. Added features for managing entries and a clean UI.
            </p>
          </article>

          <article className="timeline-item">
            <div className="timeline-header">
              <h3>Python Weather App (CLI + Flask)</h3>
              <span>Python</span>
            </div>
            <p>
              A CLI and Flask-based app to fetch current weather by city, showing both terminal
              and web interfaces for quick weather lookups.
            </p>
          </article>
        </div>
      </div>
    </section>
  );
}

export default ExperienceSection;